version: 2
workflows:
  version: 2
  foobar:
    jobs:
      - foo
      - bar
jobs:
  foo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  bar:
  docker:
    - image: circleci/ruby:2.4.1
  steps:
    - checkout
    - run: echo "A more familiar hi"
    - run: sleep 15
